#include <stdio.h>
#include "print_usage.h"

void print_usage(void)
{
    printf(
        "Usage:\n"
        "  blogtech { --serve | -s | --upload | -u } [ options ] [ args ]\n"
        "\n"
        "General options:\n"
        "  --help                  Show this message\n"
        "  --config=<path>         Load options from a config file. If the\n"
        "                          blogtech.conf file is present in the CWD,\n"
        "                          it is loaded implicitly.\n"
        "  --no-config             The default config file is ignored\n"
        "  --trace-bytes={yes|no}  Dump all I/O to stdout\n"
        "  --serve, -s             Run Blogtech as an HTTP(S) server\n"
        "  --upload, -u            Upload files to a remote Blogtech server\n"
        "\n"
        "Server options (compatible with --serve/-s):\n"
        "  --document-root=<path>  Root folder of the web content\n"
        "  --http-addr=<addr>      Local interface the HTTP server will listen on\n"
        "                          Optional. Default value is 127.0.0.1\n"
        "  --http-port=<port>      Port number the HTTP server will listen on\n"
        "                          Optional. Default value is 8080\n"
        "  --auth-password-file=<path>\n"
        "                          Path to file containing the authentication password.\n"
        "                          Required for PUT/DELETE requests. Password must be\n"
        "                          at least 32 characters.\n"
        "  --https-enabled         Enables HTTPS\n"
        "  --acme-enabled          Enables the ACME client for automatic\n"
        "                          certificate management. Requires --https-enabled\n"
        "\n"
        "  The following flags must be used alongside --https-enabled:\n"
        "    --https-addr=<addr>      Local interface the HTTPS server will listen on\n"
        "                             Optional, the default value is 127.0.0.1\n"
        "    --https-port=<port>      Port number the HTTPS server will listen on\n"
        "                             Optional. Default value is 8443\n"
        "    --cert-file=<path>       x509 certificate file path\n"
        "    --cert-key-file=<path>   Private key file associate to the certificate\n"
        "                             file\n"
        "\n"
        "  The following flags must be used alongside --acme-enabled:\n"
        "    --acme-key-file=<path>   File containing the ACME account private key\n"
        "                             Optional. Default value is acme_key.pem\n"
        "    --acme-agree-tos         Agree to the CA's terms of service\n"
        "    --acme-url=<URL>         URL of the ACME server's directory endpoint\n"
        "                             Optional. Default value refers to Let's Encrypt\n"
        "    --acme-email=<str>       E-Mail address to be associated with the ACME\n"
        "                             account and any issued certificates\n"
        "    --acme-country=<str>     Country associated to any issued certificates\n"
        "    --acme-org=<str>         Organization associated to any issued certificates\n"
        "    --acme-domain=<str>      Domain to be certified. You can specify this\n"
        "                             option multiple times to certify multiple domains\n"
        "\n"
        "Client Options (compatible with --upload/-u):\n"
        "  --remote=<url>          The URL of the target website for the uploads\n"
    );
}
