name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup environment
        run: |
           python3 -m venv venv
           ./venv/bin/pip install pylint

      - name: Run pylint
        run: |
          ./venv/bin/pylint tests
