on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

name: Release Packaging

permissions:
  contents: write

jobs:
   tests:
    uses: ./.github/workflows/testing.yaml

   changelog:
    uses: ./.github/workflows/changelog.yaml

  release:
    needs: [tests, changelog]
    name: Release Packaging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Release Build
        run: make

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes
